<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-D2KIIH1" ignored="3" name="RegressionTest(failed)(failed)" tests="2" failures="0" timestamp="2022-02-22T20:39:45 CST" time="18.738" errors="0">
  <testcase name="Forgot_Password_4B" time="4.854" classname="com.salesforce.tests.LoginTest"/>
  <testcase name="Forgot_Password_4A" time="4.958" classname="com.salesforce.tests.LoginTest"/>
  <testcase name="LoginToSalesForce2" time="0.0" classname="com.salesforce.tests.LoginTest">
    <ignored/>
  </testcase> <!-- LoginToSalesForce2 -->
  <testcase name="LoginErrorMessage1" time="0.0" classname="com.salesforce.tests.LoginTest">
    <ignored/>
  </testcase> <!-- LoginErrorMessage1 -->
  <testcase name="Check_RemeberMe_3" time="0.0" classname="com.salesforce.tests.LoginTest">
    <ignored/>
  </testcase> <!-- Check_RemeberMe_3 -->
</testsuite> <!-- RegressionTest(failed)(failed) -->
